apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: bitnami/jenkins:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: jenkins-config
          env:
            - name: JENKINS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jenkins-secret
                  key: JENKINS_PASSWORD
          volumeMounts:
            - name: jenkins-storage
              mountPath: /bitnami/jenkins
      volumes:
        - name: jenkins-storage
          persistentVolumeClaim:
            claimName: jenkins-pvc
